### ISSUE TITLE
HALT命令実行後、HALT状態が解除されない

### ISSUE THREAD

**Issue by ykominami** [toppers/athrill-target-v850e2m#5]
toppers/ev3rt-athrill-v850e2mのarch/v850_gcc/prc_support.Sのidle_loop:でhalt命令を実行後、HALT状態が解除されない。
以下のようにデバッグモードで起動し、cコマンドで実行させ、qコマンドでデバッグモードに移行し、halt命令実行の直後の状態で止まっていることを確認しました。
ここからcコマンドやiコマンドを使っても状態は変化しませんでした。

	athrill2 -c1 -i -m ../common/memory.txt -d ../common/device_config.txt -t -1 asp

HALT状態を解除する例外要求が発生しないのか、発生しても解除されないかは未確認です。

**Comment by ykominami** [comment]
ＨALＴ命令の部分をコメントにして、コンパイル・実行させても、dispather内をループするだけでした。
タスク切り替えに必要なタイムイベントが発生していないのでしょうか。

**Comment by tmori** [comment]
割り込みが上がれば，強制解除されるはずですが．．．

**Comment by ykominami** [comment]
デバッグモードのiコマンドでタイマ割り込みを掛けると、HALTが解除されることを確認しました。しかし実行可能なタスクが存在しないため、再びdispather内でidle_loopに入ります。
athrillの問題ではなく、RTOS上のアプリの設計の問題の可能性が高いです。
したがって、このissueは閉じます。
